from abc import ABCMeta, abstractmethod

from . import SimulatedExecutionHandler


class ExecutionHandler:
    """
    Handles the interaction between OrderEvent objects generated by a Portfolio and
    the ultimate set of FillEvent objects that actually occur in the market.

    Can be used to subclass simulated brokerages or live brokerages, with
    identical interfaces. This allows strategies to be backtested in a very
    similar manner to the live trading engine.
    """

    __metaclass__ = ABCMeta

    @staticmethod
    def create_new_handler(execution_type, **kwargs):
        """
        Factory method for creating new ExecutionHandler objects.
        """
        if execution_type == 'simulated':
            return SimulatedExecutionHandler(kwargs['event_queue'])

    @abstractmethod
    def execute_order(self, event):
        """
        Takes an OrderEvent object and executes it, producing
        a FillEvent object that gets placed onto the EventQueue.
        """
        raise NotImplementedError("Should implement execute_order()")
